Added a way to configure XP system messages
aontas/XPRising pull request #14
Opened 2024-05-27 22:36 UTC by nerzhei

2024-05-28 14:39 UTC, aontas requested changes
Thanks for the PR!

Overall, the idea is useful (especially for other languages). I have added some comments of things I would like changed.

2024-05-28 14:39 UTC, aontas commented on Configuration/ExperienceConfig.cs
> +        ExperienceSystem.LevelUpMessageTemplate = _configFile.Bind("Templates", "Level Up Message Template", "<color=#ffff00>Level up! You're now level</color> <color=white>{level}</color><color=#fff
```suggestion
        ExperienceSystem.XpGainedMessageTemplate = _configFile.Bind("Templates", "XP Gained Message Template", ExperienceSystem.XpGainedMessageTemplate, "Sets the template to format the message displayed when the player gains XP points. Allowed placeholders: {xpGained}, {mobLevel}, {earned}, {needed}.").Value;
        ExperienceSystem.XpLostMessageTemplate = _configFile.Bind("Templates", "XP Lost Message Template", ExperienceSystem.XpLostMessageTemplate, "Sets the template to format the message displayed when the player loses XP points. Allowed placeholders: {xpLost}, {earned}, {needed}.").Value;
        ExperienceSystem.LevelUpMessageTemplate = _configFile.Bind("Templates", "Level Up Message Template", ExperienceSystem.LevelUpMessageTemplate, "Sets the template to format the message displayed when the player levels up. Allowed placeholders: {level}.").Value;
```

2024-05-28 14:39 UTC, aontas commented on Systems/ExperienceSystem.cs
> +        public static string LevelUpMessageTemplate = "<color=#ffff00>Level up! You're now level</color> <color=white>{level}</color><color=#ffff00>!</color>";
Can you update these to match the existing log messages w.r.t the way the colour is assigned? I want to maintain the consistency of only using the colours via the `Output` constants.

2024-05-28 14:39 UTC, aontas commented on Systems/ExperienceSystem.cs
> +        public static string LevelUpMessageTemplate = "<color=#ffff00>Level up! You're now level</color> <color=white>{level}</color><color=#ffff00>!</color>";
In case you don't know, you can escape `{}` in the `$""` strings by doubling up on the braces. eg `$"{{This will print the surrounding braces instead of attempting to load a value.}}"`

2024-05-28 14:39 UTC, aontas commented on Utils/Output.cs
> +        public static void SendMessage(Entity userEntity, string template, Dictionary<string, string> values)
Instead of using a dictionary, I would much prefer you use a class that looks something like this:

```
        public class MessageTemplate
        {
            private StringBuilder sb;
            public MessageTemplate(string template)
            {
                sb = new StringBuilder(template);
            }

            public void Add(string field, string replacement)
            {
                this.sb.Replace(field, replacement);
            }

            public string Build()
            {
                return this.sb.ToString();
            }
        }
```

It can be added as an inner class to the Output class.

2024-05-28 17:56 UTC, nerzhei commented on Systems/ExperienceSystem.cs
> +        public static string LevelUpMessageTemplate = "<color=#ffff00>Level up! You're now level</color> <color=white>{level}</color><color=#ffff00>!</color>";
Updated.

2024-05-28 18:01 UTC, nerzhei commented on Utils/Output.cs
> +        public static void SendMessage(Entity userEntity, string template, Dictionary<string, string> values)
Done.

2024-05-28 18:01 UTC, nerzhei commented on Configuration/ExperienceConfig.cs
> +        ExperienceSystem.LevelUpMessageTemplate = _configFile.Bind("Templates", "Level Up Message Template", "<color=#ffff00>Level up! You're now level</color> <color=white>{level}</color><color=#fff
Done.

2024-05-28 18:08 UTC, nerzhei commented
Thanks for the feedback! I made the requested changes, feel free to point out anything else you consider 😊

2024-05-29 12:08 UTC, aontas approved these changes

2024-05-29 12:09 UTC, merged